# Generated by Django 6.0.3 on 2026-03-17 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(default='----', max_length=8, validators=[django.core.validators.RegexValidator(regex='^\\d{8}$')]),
        ),
    ]
