# Generated by Django 6.0.3 on 2026-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_pessoa_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
