# Generated by Django 6.0.3 on 2026-03-19 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_pessoa_bairro_pessoa_cidade_pessoa_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(default='----', max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{8}$')]),
        ),
    ]
