# Generated by Django 6.0.3 on 2026-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_pessoa_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(default='----', max_length=9),
        ),
    ]
